//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcadOracle.Dal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurmaHorario
    {
        public TurmaHorario()
        {
            this.Horario = new HashSet<Horario>();
        }
    
        public int Id { get; set; }
        public int TurmaId { get; set; }
        public int DiaSemana { get; set; }
    
        public virtual Turma Turma { get; set; }
        public virtual ICollection<Horario> Horario { get; set; }
    }
}
