/*
Deployment script for AcadOracleDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "AcadOracleDB"
:setvar DefaultFilePrefix "AcadOracleDB"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [$(DatabaseName)], FILENAME = N'$(DefaultDataPath)$(DefaultFilePrefix)_Primary.mdf')
    LOG ON (NAME = [$(DatabaseName)_log], FILENAME = N'$(DefaultLogPath)$(DefaultFilePrefix)_Primary.ldf') COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY NONE,
                DATE_CORRELATION_OPTIMIZATION OFF,
                DISABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
PRINT N'Creating [dbo].[Curso]...';


GO
CREATE TABLE [dbo].[Curso] (
    [Id]   INT            IDENTITY (1, 1) NOT NULL,
    [Nome] NVARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[CursoDisciplina]...';


GO
CREATE TABLE [dbo].[CursoDisciplina] (
    [CursoId]      INT NOT NULL,
    [DisciplinaId] INT NOT NULL,
    CONSTRAINT [PK_CursoDisciplina] PRIMARY KEY CLUSTERED ([CursoId] ASC, [DisciplinaId] ASC)
);


GO
PRINT N'Creating [dbo].[Disciplina]...';


GO
CREATE TABLE [dbo].[Disciplina] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [Nome]        NVARCHAR (255) NOT NULL,
    [Creditos]    INT            NOT NULL,
    [PreCreditos] INT            NOT NULL,
    [Semestre]    SMALLINT       NOT NULL,
    [Eletiva]     BIT            NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[DisciplinasPreRequisitos]...';


GO
CREATE TABLE [dbo].[DisciplinasPreRequisitos] (
    [DisciplinaId]   INT NOT NULL,
    [PreRequisitoId] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([DisciplinaId] ASC, [PreRequisitoId] ASC)
);


GO
PRINT N'Creating [dbo].[TipoUsuario]...';


GO
CREATE TABLE [dbo].[TipoUsuario] (
    [Id]        INT        NOT NULL,
    [Descricao] NCHAR (20) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Turma]...';


GO
CREATE TABLE [dbo].[Turma] (
    [Id]           INT           IDENTITY (1, 1) NOT NULL,
    [DisciplinaId] INT           NOT NULL,
    [Numero]       INT           NOT NULL,
    [TurmaHorario] NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Usuario]...';


GO
CREATE TABLE [dbo].[Usuario] (
    [Id]            INT         IDENTITY (1, 1) NOT NULL,
    [TipoUsuarioId] INT         NOT NULL,
    [Nome]          NCHAR (100) NOT NULL,
    [Email]         NCHAR (255) NOT NULL,
    [Senha]         NCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating FK_CursoDisciplina_Curso...';


GO
ALTER TABLE [dbo].[CursoDisciplina] WITH NOCHECK
    ADD CONSTRAINT [FK_CursoDisciplina_Curso] FOREIGN KEY ([CursoId]) REFERENCES [dbo].[Curso] ([Id]);


GO
PRINT N'Creating FK_CursoDisciplina_Disciplina...';


GO
ALTER TABLE [dbo].[CursoDisciplina] WITH NOCHECK
    ADD CONSTRAINT [FK_CursoDisciplina_Disciplina] FOREIGN KEY ([DisciplinaId]) REFERENCES [dbo].[Disciplina] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_DisciplinasPreRequisitos_Disciplina...';


GO
ALTER TABLE [dbo].[DisciplinasPreRequisitos] WITH NOCHECK
    ADD CONSTRAINT [FK_DisciplinasPreRequisitos_Disciplina] FOREIGN KEY ([DisciplinaId]) REFERENCES [dbo].[Disciplina] ([Id]);


GO
PRINT N'Creating FK_DisciplinasPreRequisitos_PreRequisito...';


GO
ALTER TABLE [dbo].[DisciplinasPreRequisitos] WITH NOCHECK
    ADD CONSTRAINT [FK_DisciplinasPreRequisitos_PreRequisito] FOREIGN KEY ([PreRequisitoId]) REFERENCES [dbo].[Disciplina] ([Id]);


GO
PRINT N'Creating FK_Turma_Disciplina...';


GO
ALTER TABLE [dbo].[Turma] WITH NOCHECK
    ADD CONSTRAINT [FK_Turma_Disciplina] FOREIGN KEY ([DisciplinaId]) REFERENCES [dbo].[Disciplina] ([Id]);


GO
PRINT N'Creating FK_Usuario_TipoUsuario...';


GO
ALTER TABLE [dbo].[Usuario] WITH NOCHECK
    ADD CONSTRAINT [FK_Usuario_TipoUsuario] FOREIGN KEY ([TipoUsuarioId]) REFERENCES [dbo].[TipoUsuario] ([Id]);


GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

GO

--Adiciona o curso de CC
DELETE FROM CursoDisciplina;
DELETE FROM Curso;

INSERT INTO [dbo].[Curso]
           ([Nome])
     VALUES
           ('Ciências da Computação')
GO


DELETE FROM DisciplinasPreRequisitos;
DELETE FROM Turma;
DELETE FROM Disciplina;

DECLARE @semestre INT = 1;
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Matematica Discreta',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Calculo A',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Geometria Analitica',2 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Algoritmos e Programacao I',6 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Introducao A Ciencia da Computacao',4 , 0, @semestre,0);	

SET @semestre = 2;

INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Calculo B',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Algebra Matricial',2 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Algoritmos e Programacao II',6 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Logica para Computacao',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Linguagens Formais',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Organizacao e Arquit. de Computadores I',4 , 0, @semestre,0);	


SET @semestre = 3;

INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Modelagem de Software',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Laboratorio de Banco de Dados I',2 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Algoritmos e Programacao III',6 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Paradigmas de Linguagens de Programacao',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Teoria da Computacao',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Organizacao e Arquit. de Computadores II',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Programacao para Software Basico',4 , 0, @semestre,0);	

SET @semestre = 4;

INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Modelagem Conceit. e Proj. de Banco Dados',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Complexidade e Otimizacao',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Tecnicas de Programacao',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Computacao Grafica I',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Organizacao e Arquit. de Computadores III',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Compiladores',4 , 0, @semestre,0);	

SET @semestre = 5;

INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Metodos Estatisticos',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Gerencia de Projetos de Software',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Projeto de Interfaces',2 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Metodos Formais para Computacao',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Computacao Grafica II',2 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Sistemas Operacionais',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Redes de Computadores I',4 , 0, @semestre,0);	

SET @semestre = 6;

INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Desenvolvimento de Sistemas',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Implementacao de Banco de Dados',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Entretenimento Digital',2 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Inteligencia Artificial',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Metodos Computacionais',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Programacao de Perifericos',2 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Redes de Computadores II',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Laboratorio de Redes de Computadores',2 , 0, @semestre,0);	

SET @semestre = 7;

INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Humanismo e Cultura Religiosa',4 , 60, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Trabalho de Conclusao I',4 , 100, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Avaliacao de Desempenho de Sistemas',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Redes de Computadores III',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Programacao Paralela',2 , 0, @semestre,0);	

SET @semestre = 8;

INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Etica e Filosofia da Ciencia',4 , 60, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Empreendimentos Empresariais',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Trabalho de Conclusao II',4 , 0, @semestre,0);	
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Sistemas Embarcados',4 , 0, @semestre,0);
INSERT INTO [dbo].[Disciplina] ([Nome], [Creditos], [PreCreditos], [Semestre], [Eletiva])
VALUES ('Programacao Distribuida',4 , 0, @semestre,0);

GO

INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Calculo B'), (SELECT ID FROM Disciplina WHERE Nome='Calculo A'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao II'), (SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao I'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Linguagens Formais'), (SELECT ID FROM Disciplina WHERE Nome='Matematica Discreta'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Linguagens Formais'), (SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao I'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Organizacao e Arquit. de Computadores I'), (SELECT ID FROM Disciplina WHERE Nome='Introducao A Ciencia da Computacao'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Logica para Computacao'), (SELECT ID FROM Disciplina WHERE Nome='Matematica Discreta'));

INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Teoria da Computacao'), (SELECT ID FROM Disciplina WHERE Nome='Logica para Computacao'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Paradigmas de Linguagens de Programacao'), (SELECT ID FROM Disciplina WHERE Nome='Logica para Computacao'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Paradigmas de Linguagens de Programacao'), (SELECT ID FROM Disciplina WHERE Nome='Linguagens Formais'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Paradigmas de Linguagens de Programacao'), (SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao II'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Organizacao e Arquit. de Computadores II'), (SELECT ID FROM Disciplina WHERE Nome='Organizacao e Arquit. de Computadores I'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Laboratorio de Banco de Dados I'), (SELECT ID FROM Disciplina WHERE Nome='Matematica Discreta'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Modelagem de Software'), (SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao II'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Programacao para Software Basico'), (SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao II'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao III'), (SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao II'));

INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Organizacao e Arquit. de Computadores III'), (SELECT ID FROM Disciplina WHERE Nome='Organizacao e Arquit. de Computadores II'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Compiladores'), (SELECT ID FROM Disciplina WHERE Nome='Organizacao e Arquit. de Computadores II'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Compiladores'), (SELECT ID FROM Disciplina WHERE Nome='Paradigmas de Linguagens de Programacao'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Modelagem Conceit. e Proj. de Banco Dados'), (SELECT ID FROM Disciplina WHERE Nome='Laboratorio de Banco de Dados I'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Tecnicas de Programacao'), (SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao III'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Complexidade e Otimizacao'), (SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao III'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Computacao Grafica I'), (SELECT ID FROM Disciplina WHERE Nome='Algebra Matricial'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Computacao Grafica I'), (SELECT ID FROM Disciplina WHERE Nome='Programacao para Software Basico'));

INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Metodos Formais para Computacao'), (SELECT ID FROM Disciplina WHERE Nome='Logica para Computacao'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Redes de Computadores I'), (SELECT ID FROM Disciplina WHERE Nome='Programacao para Software Basico'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Sistemas Operacionais'), (SELECT ID FROM Disciplina WHERE Nome='Programacao para Software Basico'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Projeto de Interfaces'), (SELECT ID FROM Disciplina WHERE Nome='Modelagem de Software'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Gerencia de Projetos de Software'), (SELECT ID FROM Disciplina WHERE Nome='Modelagem de Software'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Computacao Grafica II'), (SELECT ID FROM Disciplina WHERE Nome='Computacao Grafica I'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Metodos Estatisticos'), (SELECT ID FROM Disciplina WHERE Nome='Calculo A'));

INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Laboratorio de Redes de Computadores'), (SELECT ID FROM Disciplina WHERE Nome='Redes de Computadores I'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Redes de Computadores II'), (SELECT ID FROM Disciplina WHERE Nome='Redes de Computadores I'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Programacao de Perifericos'), (SELECT ID FROM Disciplina WHERE Nome='Sistemas Operacionais'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Implementacao de Banco de Dados'), (SELECT ID FROM Disciplina WHERE Nome='Modelagem Conceit. e Proj. de Banco Dados'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Desenvolvimento de Sistemas'), (SELECT ID FROM Disciplina WHERE Nome='Modelagem Conceit. e Proj. de Banco Dados'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Desenvolvimento de Sistemas'), (SELECT ID FROM Disciplina WHERE Nome='Tecnicas de Programacao'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Desenvolvimento de Sistemas'), (SELECT ID FROM Disciplina WHERE Nome='Gerencia de Projetos de Software'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Inteligencia Artificial'), (SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao III'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Entretenimento Digital'), (SELECT ID FROM Disciplina WHERE Nome='Computacao Grafica I'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Metodos Computacionais'), (SELECT ID FROM Disciplina WHERE Nome='Algoritmos e Programacao I'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Metodos Computacionais'), (SELECT ID FROM Disciplina WHERE Nome='Calculo B'));

INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Redes de Computadores III'), (SELECT ID FROM Disciplina WHERE Nome='Redes de Computadores II'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Programacao Paralela'), (SELECT ID FROM Disciplina WHERE Nome='Sistemas Operacionais'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Avaliacao de Desempenho de Sistemas'), (SELECT ID FROM Disciplina WHERE Nome='Metodos Estatisticos'));

INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Programacao Distribuida'), (SELECT ID FROM Disciplina WHERE Nome='Redes de Computadores I'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Sistemas Embarcados'), (SELECT ID FROM Disciplina WHERE Nome='Programacao Paralela'));
INSERT INTO [dbo].DisciplinasPreRequisitos ([DisciplinaId], [PreRequisitoId]) VALUES ((SELECT ID FROM Disciplina WHERE Nome='Trabalho de Conclusao II'), (SELECT ID FROM Disciplina WHERE Nome='Trabalho de Conclusao I'));

GO

INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Algoritmos e Programacao I'), 128, '2JK4JK6JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Algoritmos e Programacao I'), 138, '2JK4JK6JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Algoritmos e Programacao I'), 148, '2NP4NP6NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Calculo A'), 128, '2LM4LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Calculo A'), 138, '2LM4LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Geometria Analitica'), 128, '6LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Geometria Analitica'), 138, '6LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Introducao a Ciencia da Computacao'), 128, '3LM5LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Introducao a Ciencia da Computacao'), 138, '3LM5LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Matematica Discreta'), 128, '3JK5JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Matematica Discreta'), 138, '3NP5NP');

INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='algebra Matricial'), 128, '3NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='algebra Matricial'), 138, '3LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Algoritmos e Programacao II'), 128, '2JK4JK6JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Algoritmos e Programacao II'), 138, '2LM4LM6LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Algoritmos e Programacao II'), 148, '2JK4JK6JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Calculo B'), 128, '2NP4NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Calculo B'), 138, '2NP4NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Linguagens Formais'), 128, '3LM5LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Linguagens Formais'), 138, '3JK5JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Logica para Computacao'), 128, '3JK5JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Logica para Computacao'), 138, '2LM4LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Organizacao e Arquit. de Computadores I'), 128, '2LM4LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Organizacao e Arquit. de Computadores I'), 138, '2JK4JK');

INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Algoritmos e Programacao III'), 128, '2LM4LM6LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Algoritmos e Programacao III'), 138, '2JK4JK6JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Algoritmos e Programacao III'), 148, '2JK4JK6JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Laboratorio de Banco de Dados I'), 128, '6JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Laboratorio de Banco de Dados I'), 138, '6LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Laboratorio de Banco de Dados I'), 148, '6LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Modelagem de Software'), 128, '2NP4NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Modelagem de Software'), 138, '2LM4LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Organizacao e Arquit. de Computadores II'), 128, '3JK5JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Paradigmas de Linguagens de Programacao'), 128, '3LM5LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Programacao para Software Basico'), 128, '2JK4JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Programacao para Software Basico'), 138, '2NP4NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Teoria da Computacao'), 128, '3NP5NP');

INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Compiladores'), 128, '3LM5LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Complexidade e Otimizacao'), 128, '2NP4NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Computacao Grafica I'), 128, '2JK4JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Modelagem Conceit. e Proj. de Banco Dados'), 128, '2LM4LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Organizacao e Arquit. de Computadores III'), 128, '3JK5JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='TEcnicas de Programacao'), 128, '3NP5NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='TEcnicas de Programacao'), 138, '3JK5JK');

INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Computacao Grafica II'), 128, '3JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Gerencia de Projetos de Software'), 128, '3LM5LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='MEtodos Estatisticos'), 128, '3NP5NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='MEtodos Formais para Computacao'), 128, '2LM4LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Projeto de Interfaces'), 128, '5JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Projeto de Interfaces'), 138, '6JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Redes de Computadores I'), 128, '2JK4JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Sistemas Operacionais'), 128, '2NP4NP');

INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Desenvolvimento de Sistemas'), 128, '3NP5NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Entretenimento Digital'), 128, '2JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Implementacao de Banco de Dados'), 128, '2NP4NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Inteligencia Artificial'), 128, '3LM5LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Laboratorio de Redes de Computadores'), 128, '6JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Laboratorio de Redes de Computadores'), 138, '6LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='MEtodos Computacionais'), 128, '2LM4LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Programacao de PerifEricos'), 128, '4JK');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Redes de Computadores II'), 128, '3JK5JK');

INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Empreendimentos Empresariais'), 128, '3LM5LM');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Etica e Filosofia da Ciencia'), 128, '6LM6NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Programacao Distribuida'), 128, '3NP5NP');
INSERT INTO Turma (DisciplinaId, Numero, TurmaHorario) VALUES((SELECT Id FROM Disciplina WHERE Nome='Sistemas Embarcados'), 128, '2LM4LM');

GO

--Adiciona as disciplinas no curso de CC.
DECLARE @CursoId INT;
SELECT TOP 1 @CursoId = Id FROM Curso;

INSERT INTO [dbo].[CursoDisciplina]
           ([CursoId]
           ,[DisciplinaId])
SELECT @CursoId, Id FROM Disciplina;

GO

--GRANT Super User permission to the AppPool on the database.
IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'IIS APPPOOL\AcadOracleAppPool')
BEGIN
    CREATE LOGIN [IIS APPPOOL\AcadOracleAppPool] 
      FROM WINDOWS WITH DEFAULT_DATABASE=[master], 
      DEFAULT_LANGUAGE=[us_english]
END
GO
CREATE USER [AcadOracleSA] 
  FOR LOGIN [IIS APPPOOL\AcadOracleAppPool]
GO
EXEC sp_addrolemember 'db_owner', 'AcadOracleSA'

GO

GO

--GRANT Super User permission to the AppPool on the database.
IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'IIS APPPOOL\DefaultAppPool')
BEGIN
    CREATE LOGIN [IIS APPPOOL\DefaultAppPool] 
      FROM WINDOWS WITH DEFAULT_DATABASE=[master], 
      DEFAULT_LANGUAGE=[us_english]
END
GO
CREATE USER [AcadOracleSA2] 
  FOR LOGIN [IIS APPPOOL\DefaultAppPool]
GO
EXEC sp_addrolemember 'db_owner', 'AcadOracleSA2'
GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[CursoDisciplina] WITH CHECK CHECK CONSTRAINT [FK_CursoDisciplina_Curso];

ALTER TABLE [dbo].[CursoDisciplina] WITH CHECK CHECK CONSTRAINT [FK_CursoDisciplina_Disciplina];

ALTER TABLE [dbo].[DisciplinasPreRequisitos] WITH CHECK CHECK CONSTRAINT [FK_DisciplinasPreRequisitos_Disciplina];

ALTER TABLE [dbo].[DisciplinasPreRequisitos] WITH CHECK CHECK CONSTRAINT [FK_DisciplinasPreRequisitos_PreRequisito];

ALTER TABLE [dbo].[Turma] WITH CHECK CHECK CONSTRAINT [FK_Turma_Disciplina];

ALTER TABLE [dbo].[Usuario] WITH CHECK CHECK CONSTRAINT [FK_Usuario_TipoUsuario];


GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
PRINT N'Update complete.';


GO
